### PR TITLE
feat: better help text

### PR DESCRIPTION
**Pull request by himanshu-dixit**
| :rocket: | This description was created by [Ellipsis](https://www.ellipsis.dev) for commit 01f68c18e2c180d321faab4f6a79a1b0f6783949  | 
|--------|--------|

### Summary:
This PR enhances the help text, formatting, and command descriptions across various CLI commands in the Composio project, with specific updates to `composio/cli/__init__.py` and improvements in command descriptions.

**Key points**:
- Enhanced help text for CLI commands using `HelpfulCmdBase`.
- Added usage examples for each command.
- Improved formatting and information display in help sections.
- Updated help text in `composio/cli/__init__.py`.
- Modified `format_help` in `RichGroup` class.
- Enhanced descriptions for `composio add github` and `composio login` commands.
- Corrected example usage in `composio/cli/login.py`.
- Added usage examples and improved help text formatting across CLI commands.

----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Comment by sohamganatra** [comment]
[https://github.com/SamparkAI/composio/pull/94#issuecomment-2146989338](https://github.com/SamparkAI/composio/pull/94#issuecomment-2146989338)

**Comment by sohamganatra** [comment]
Check out the code feedback.

**Review by utkarsh-dixit — APPROVED** [review]

**Comment by himanshu-dixit** [comment]
@sohamganatra Had checked. We're ovverriding the click and following patterns of it.

- For logout we have added check.
- black text is defaulting to grey in terminal.

**Pull request merged**
